# Generated by Django 2.2.5 on 2019-09-06 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190907_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 3, 43, 32, 555196)),
        ),
    ]
